### ISSUE TITLE
Get NYU DH site linked from NYU pages

### ISSUE THREAD

**Issue by mnyrop** [nyu-dh/website#128]
Submit requests to have NYU pages link to https://digitalhumanities.nyu.edu

- [x] https://library.nyu.edu/departments/digital-scholarship-services/
- [x] https://guides.nyu.edu/digital-humanities/
- [x] https://www.nyu.edu/life/information-technology/research-computing-services/research-data-and-tools/digital-humanities.html
- [x] https://nyuhumanities.org/program/digital-humanities-program/
- [x] https://wp.nyu.edu/fas-edtech/services/digital_pedagogy/

**Comment by coblezc** [comment]
I'd start with Bobby

**Comment by mnyrop** [comment]
@coblezc thanks for adding to DH agenda tomorrow. I can follow up on any action items that emerge from the meeting
